#!/bin/python

import os
import sys
import subprocess
from parsing.parse import parse
from functools import reduce

layouts = []

for filename in os.listdir(sys.argv[1]):
    with  open(os.path.join(sys.argv[1], filename), 'r') as f:
        layouts += [parse(f)]

rofi_input_string = reduce(lambda res, nxt: res + '\n' + nxt, map(lambda lay: lay.name, layouts))

rofi = subprocess.Popen(['rofi', '-dmenu'], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.STDOUT)

chosen_layout_string = (rofi.communicate(input=rofi_input_string.encode('UTF-8'))[0]).decode('UTF-8').strip('\n')

chosen_layout = list(filter(lambda lay: lay.name == chosen_layout_string, layouts))[0]

subprocess.call(['xrandr'] + chosen_layout.to_XRandR_Options())
