#!/bin/python

import sys
from application.apply import apply
from parsing.parse import parse

# parse and apply the layout file provided via commandline argument

layout_file = sys.argv[1]

with open(layout_file, 'r') as f:
    layout = parse(f)
    apply(layout)
