#!/bin/python

import os
import sys
from parsing.parse import parse
from application.apply import apply
from requesting.request import request, get_request_options

layouts_dir = sys.argv[1]
bg_color = sys.argv[2]
text_color = sys.argv[3]
inactive_bg_color = sys.argv[4]
inactive_text_color = sys.argv[5]
font = sys.argv[6]

layouts = []

for filename in os.listdir(sys.argv[1]):
    with  open(os.path.join(sys.argv[1], filename), 'r') as f:
        layouts += [parse(f)]

request_options = get_request_options(bg_color, text_color, inactive_bg_color, inactive_text_color, font)

chosen_layout_string = request(layouts, request_options)

chosen_layouts = list(filter(lambda lay: lay.name == chosen_layout_string, layouts))

if len(chosen_layouts) > 0:
    apply(chosen_layouts[0])


